Repository haruconnection-v2/Haru, pull requests merged in 2024-09, with the labels that each got.

#5 [chore] 초기 세팅
  .gitmessage.txt
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/backend/BackendApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/backend/BackendApplicationTests.java
Labels: chore

#8 issue, pr 템플릿
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/pull_request_template.md
Labels: ⚙️chore

#10 feature : Dockerfile 설정
  backend/Dockerfile
  backend/build.gradle
  backend/src/main/resources/application.properties
  docker-compose.yml
Labels: 🪄feature

#13 chore: 네이버 코딩 컨벤션, checkstyle 적용
  backend/naver-checkstyle-rules.xml
  backend/naver-intellij-formatter.xml
Labels: ⚙️chore

#15 feature : Calendar 도메인 생성 및 swagger 연동
  backend/build.gradle
  backend/src/main/java/com/backend/domain/calendar/controller/CalendarController.java
  backend/src/main/java/com/backend/domain/calendar/entity/Calendar.java
  backend/src/main/java/com/backend/domain/calendar/repository/CalendarRepository.java
  backend/src/main/java/com/backend/domain/calendar/service/CalendarService.java
  backend/src/main/java/com/backend/domain/calendar/service/CalendarServiceImpl.java
  backend/src/main/java/com/backend/global/config/JPAConfig.java
  backend/src/main/java/com/backend/global/config/SwaggerConfig.java
  backend/src/main/resources/application.properties
Labels: 🪄feature
